ENV_VAR_RW: "db_one_readwrite"
CONS_WEB_PORT: "0.0.0.0:8989"
ENV_RUN_ENV : "Started service running as " 

database:
  db_one_readwrite:
    dbname: "BSE_Equity_Db"
    dbuser: "root"
    dbpassword: "root#123PD"
    hostname: "127.0.0.1:3360"

